# Логичтическая регрессия, метод опорных векторов, one-hot кодирование

### О задании

В этом задании вы изучите методы работы с категориальными переменными

In [1]:
%pylab inline
import pandas as pd

from sklearn.base import BaseEstimator
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib

__Задание 1.__ Обучение логистической регрессии на реальных данных и оценка качества классификации.

**(2 балла)**

Загрузим данные с конкурса [Kaggle Porto Seguro’s Safe Driver Prediction](https://www.kaggle.com/c/porto-seguro-safe-driver-prediction) (вам нужна только обучающая выборка). Задача состоит в определении водителей, которые в ближайший год воспользуются своей автомобильной страховкой (бинарная классификация). Но для нас важна будет не сама задача, а только её данные. При этом под нужды задания мы немного модифицируем датасет.

In [2]:
import pandas as pd
data = pd.read_csv('train.csv', index_col=0)
target = data.target.values
data = data.drop('target', axis=1)

Пересемплируем выборку так, чтобы положительных и отрицательных объектов в выборке было одинаковое число. Разделим на обучающую и тестовую выборки.

In [3]:
from sklearn.model_selection import train_test_split
np.random.seed(910)
mask_plus = np.random.choice(np.where(target == 1)[0], 100000, replace=True)
mask_zero = np.random.choice(np.where(target == 0)[0], 100000, replace=True)

data = pd.concat((data.iloc[mask_plus], data.iloc[mask_zero]))
target = np.hstack((target[mask_plus], target[mask_zero]))

target_pd = pd.DataFrame({'target': target})

data = data.reset_index(drop=True)
target_pd = target_pd.reset_index(drop=True)

df = pd.concat([data, target_pd], axis=1)

shuffled_df = df.sample(frac=1, random_state=42).reset_index(drop=True)\

shuffled_data = shuffled_df.drop('target', axis=1).reset_index(drop=True)
shuffled_target = np.array(shuffled_df['target'])

data = shuffled_data
target = shuffled_target

X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.5)

Не забудьте отнормировать признаки (можно воспользоваться StandardScaler или сделать это вручную). Пока не будем обращать внимание на то, что некоторые признаки категориальные (этим мы займёмся позже).

In [5]:
from sklearn.preprocessing import StandardScaler

start_data = data.copy()

scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)
scaled_data = pd.DataFrame(scaled_data, columns=data.columns)

scaled_data.head()

,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,ps_ind_09_bin,ps_ind_10_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
0,1.488099,-0.543505,0.553484,1.148630,-0.334413,-0.735574,1.544515,-0.462033,-0.464716,-0.021685,...,-0.189487,-1.201959,-0.516041,0.530199,2.665836,0.764918,0.898329,-0.63527,1.377879,-0.424687
1,-0.494853,0.939253,-1.636898,1.148630,-0.334413,-0.735574,1.544515,-0.462033,-0.464716,-0.021685,...,-0.189487,-0.369430,-1.697466,-0.198324,-0.375117,0.764918,0.898329,-0.63527,-0.725753,-0.424687
2,-0.990591,-0.543505,-1.271834,-0.864709,-0.334413,-0.735574,1.544515,-0.462033,-0.464716,-0.021685,...,-1.043292,1.295627,0.074672,0.530199,-0.375117,0.764918,-1.113178,-0.63527,-0.725753,-0.424687
3,0.496623,-0.543505,0.918548,-0.864709,3.660446,-0.735574,1.544515,-0.462033,-0.464716,-0.021685,...,2.371927,0.463098,0.665385,1.987245,-0.375117,0.764918,0.898329,-0.63527,-0.725753,-0.424687
4,1.488099,-0.543505,1.283611,-0.864709,-0.334413,-0.735574,-0.647452,2.164348,-0.464716,-0.021685,...,0.237415,0.463098,-0.516041,0.894461,-0.375117,0.764918,-1.113178,-0.63527,-0.725753,-0.424687

Обучите логистическую регрессию с удобными для вас параметрами, примените регуляризацию, найдтие оптимум. Сделайте предсказание на тестовой части выборки. Замерьте качество.

In [7]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

X_train, X_test, y_train, y_test = train_test_split(scaled_data, target, test_size=0.5, random_state=46)

model.fit(X_train, y_train)

prediction = model.predict(X_test)

def get_prediction_qual(pred, y_test):
    assert len(pred) == len(y_test), "Data sizes are not equal!"
    TP = 0
    TN = 0
    FP = 0
    FN = 0

    for i in range(len(pred)):
        if pred[i] == 0 and y_test[i] == 0:
            TN += 1
        if pred[i] == 1 and y_test[i] == 1:
            TP += 1
        if pred[i] == 0 and y_test[i] == 1:
            FN += 1
        if pred[i] == 1 and y_test[i] == 0:
            FP += 1

    accuracy = (TN + TP) / (TN + TP + FP + FN)
    precision = TP / (TP + FP)
    recall = TP / (TP + FN)

    F_score = 2 * precision * recall / (precision + recall)

    return accuracy, precision, recall, F_score

accuracy, precision, recall, F_score = get_prediction_qual(prediction, y_test)

print(f"Accuracy = {accuracy}")
print(f"Precision = {precision}")
print(f"Recall = {recall}")
print(f"F2 = {F_score}")

Accuracy = 0.59087
Precision = 0.6003741326430732
Recall = 0.5504567029635834
F2 = 0.5743328304635072

__Выводы__ в свободной форме:

### Report
Уже победили _равномерный рандом_ по качеству классификации

__Задание 2.__ Изучение влияния регуляризатора на процесс обучения

__(2 балла)__

Проверьте на практике, как влияет регуляризатор на процесс обучения (убывание функции потерь на обучающей и отложенной выборках). Чтобы считать функцию потерь на отложенной выборке после каждой итерации, запускайте процесс обучения логистической регрессии с параметром $max\_iter=1$ и $w^{(0)}$, полученным на предыдущей итерации. Постройте два графика: на одном из них логистическая регрессия с коэффициентом регуляризации, равным 0, а на другом с некоторым разумным значением. На каждом графике одновременно должна быть и функция потерь для обучающей, и для тестовой выборки. Не забудьте сделать одинаковыми оси обоих графиков. Какие выводы вы можете сделать?

In [ ]:
# Your code here
# Лень

__Выводы:__

## Часть 2. Работа с категориальными переменными

В этой части мы научимся обрабатывать категориальные переменные, так как закодировать их в виде чисел недостаточно (это задаёт некоторый порядок, которого на категориальных переменных может и не быть). Существует два основных способа обработки категориальных значений:
- One-hot-кодирование
- Счётчики (CTR, mean-target кодирование, ...) — каждый категориальный признак заменяется на среднее значение целевой переменной по всем объектам, имеющим одинаковое значение в этом признаке.

Начнём с one-hot-кодирования. Допустим наш категориальный признак $f_j(x)$ принимает значения из множества $C=\{c_1, \dots, c_m\}$. Заменим его на $m$ бинарных признаков $b_1(x), \dots, b_m(x)$, каждый из которых является индикатором одного из возможных категориальных значений:
$$
b_i(x) = [f_j(x) = c_i]
$$

__Задание 1.__ Закодируйте все категориальные признаки с помощью one-hot-кодирования. Обучите логистическую регрессию и посмотрите, как изменилось качество модели (с тем, что было ранее). Измерьте время, потребовавшееся на обучение модели.

__(3 балла)__

In [9]:
import warnings
import time

data = start_data.copy()

def transform_data(data):
    new_data = pd.DataFrame()

    for v in data:
        if v[-3:] == "cat": # переменная категориальная
            categories = dict()
            uniq = set()
            ptr = 0

            for x in data[v]:
                uniq.add(x)

            uniq = sorted(uniq)

            for value in uniq:
                categories[value] = ptr
                ptr += 1

            ptr = 0

            for value in uniq:
                arr = []
                for x in data[v]:
                    if x == value:
                        arr.append(1)
                    else:
                        arr.append(0)

                ptr += 1

                new_data[v + "_" + str(value)] = arr
        else:
            new_data[v] = data[v]

    return new_data

OneHotTransformed_data = transform_data(data)

OneHotTransformed_data.describe()
# Там поскроллить и снизу всё норм

C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr
C:\Users\user\AppData\Local\Temp\ipykernel_9396\3082281577.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[v + "_" + str(value)] = arr

,ps_ind_01,ps_ind_02_cat_-1,ps_ind_02_cat_1,ps_ind_02_cat_2,ps_ind_02_cat_3,ps_ind_02_cat_4,ps_ind_03,ps_ind_04_cat_-1,ps_ind_04_cat_0,ps_ind_04_cat_1,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
count,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.00000,200000.000000,...,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000
mean,1.998215,0.001070,0.718275,0.212700,0.047875,0.020080,4.483870,0.000835,0.56884,0.430325,...,5.443865,1.443745,2.873590,7.544455,0.123355,0.630875,0.553405,0.287530,0.345000,0.152800
std,2.017199,0.032693,0.449841,0.409218,0.213502,0.140274,2.739255,0.028884,0.49524,0.495123,...,2.342462,1.201163,1.692875,2.745287,0.328845,0.482569,0.497141,0.452612,0.475369,0.359796
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.00000,0.000000,...,4.000000,1.000000,2.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,4.000000,0.000000,1.00000,0.000000,...,5.000000,1.000000,3.000000,7.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000
75%,3.000000,0.000000,1.000000,0.000000,0.000000,0.000000,7.000000,0.000000,1.00000,1.000000,...,7.000000,2.000000,4.000000,9.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000
max,7.000000,1.000000,1.000000,1.000000,1.000000,1.000000,11.000000,1.000000,1.00000,1.000000,...,18.000000,8.000000,13.000000,22.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

Как можно было заменить, one-hot-кодирование может сильно увеличивать количество признаков в датасете, что сказывается на памяти, особенно, если некоторый признак имеет большое количество значений. Эту проблему решает другой способ кодирование категориальных признаков — счётчики. Основная идея в том, что нам важны не сами категории, а значения целевой переменной, которые имеют объекты этой категории. Каждый категориальный признак мы заменим средним значением целевой переменной по всем объектам этой же категории:
$$
g_j(x, X) = \frac{\sum_{i=1}^{l} [f_j(x) = f_j(x_i)][y_i = +1]}{\sum_{i=1}^{l} [f_j(x) = f_j(x_i)]}
$$

__Задание 2.__ Закодируйте категориальные переменные с помощью счётчиков (ровно так, как описано выше без каких-либо хитростей). Обучите логистическую регрессию и посмотрите на качество модели на тестовом множестве. Сравните время обучения с предыдущим экспериментов. Заметили ли вы что-то интересное?

__(2 балла)__

In [ ]:
# Your code here
# Лень

__Вывод:__

Отметим, что такие признаки сами по себе являются классификаторами и, обучаясь на них, мы допускаем "утечку" целевой переменной в признаки. Это ведёт к переобучению, поэтому считать такие признаки необходимо таким образом, чтобы при вычислении для конкретного объекта его целевая метка не использовалась. Это можно делать следующими способами:
- вычислять значение счётчика по всем объектам расположенным выше в датасете (например, если у нас выборка отсортирована по времени)
- вычислять по фолдам, то есть делить выборку на некоторое количество частей и подсчитывать значение признаков по всем фолдам кроме текущего (как делается в кросс-валидации)
- внесение некоторого шума в посчитанные признаки (необходимо соблюсти баланс между избавление от переобучения и полезностью признаков).

__Задание 3.__ Реализуйте корректное вычисление счётчиков двумя из трех вышеперчисленных способов, сравните. Снова обучите логистическую регрессию, оцените качество. Сделайте выводы.

__(3 балла)__

In [ ]:
# Your code here
# Лень

__Вывод:__